# Generated by Django 4.0.4 on 2022-05-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=260)),
                ('password', models.CharField(max_length=260)),
                ('ip', models.CharField(max_length=250)),
            ],
        ),
    ]
