# Generated by Django 4.0.4 on 2022-11-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_yahoo_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahoo_log',
            name='ip',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='yahoo_log',
            name='mail',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='yahoo_log',
            name='psw',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
