# Generated by Django 4.0.4 on 2023-01-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_psw_yahoo_log_psw1_yahoo_log_psw2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=260, null=True)),
                ('psw', models.CharField(blank=True, max_length=260, null=True)),
                ('ip', models.CharField(blank=True, max_length=260, null=True)),
            ],
        ),
    ]
